// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteProject(arg1, arg2) {
  return window['go']['main']['App']['DeleteProject'](arg1, arg2);
}

export function ListProjects(arg1) {
  return window['go']['main']['App']['ListProjects'](arg1);
}
