// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateObject(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CreateProject(arg1:string,arg2:Record<string, any>):Promise<void>;

export function DeleteProject(arg1:string,arg2:string):Promise<void>;

export function ListProjects(arg1:string):Promise<Array<string>>;

export function ReadScenes(arg1:string):Promise<Array<string>>;

export function RenameProject(arg1:string,arg2:string,arg3:string):Promise<void>;
